# https://gitlab.com/pkp-org/docker/ojs
# set vars: SERVER_URL SERVERIPADDR OJS_DB_HOST OJS_DB_USER OJS_DB_PASSWORD OJS_DB_NAME OJS_DATAFILES
#   OJS_VERSION : 3_3_0-13
version: "3.6"

services:
  eademfoco:
    image: pkpofficial/ojs:${OJS_VERSION}
    labels:
      - traefik.enable=true
      - traefik.http.routers.eademfoco.rule=Host(`${SERVER_URL}`)
      - traefik.http.routers.eademfoco.tls=true
      - traefik.http.services.eademfoco.loadbalancer.server.port=80
      - traefik.http.routers.eademfoco.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
    extra_hosts:
      - "${SERVER_URL}:${SERVERIPADDR}" # for new install only
    environment:
      - OJS_CLI_INSTALL=1  # autoupdate
      - SERVER_URL  
      - OJS_DB_DRIVER=mysqli
      - OJS_DB_HOST
      - OJS_DB_USER
      - OJS_DB_PASSWORD
      - OJS_DB_NAME
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./favicon.ico:/var/www/html/favicon.ico:ro
      - ojs-files:/var/www/files
    restart: unless-stopped
    
volumes:
  ojs-files:
     driver_opts:
           type: none
           device: ${OJS_DATAFILES}
           o: bind
           
networks:
  proxy_default:
    external: true
